### PR TITLE
Fix wrong fajr and sunrise time

### LINKED ISSUE #1: Wrong Fajr and Sunrise times are being reported for some time zones
I'm struggling to pass more config. I've pretty good result with the code below:

```rust
fn get_prayers_time() -> Result<salah::PrayerTimes, String> {
    let city = Coordinates::new(-7.1605439, 113.4826273);
    let date = Utc::today();
   let params = Configuration::with(Method::Singapore, Madhab::Shafi);    
    let prayers = PrayerSchedule::new()
        .on(date)
        .for_location(city)
        .with_configuration(params)
        .calculate();
    return prayers;
}

```

Unfortunately, the fajr and sunrise time is wrong. But other time are correct:

```
Fajr: 7:59 AM <--- it should 03:59 AM
Sunrise: 7:14 AM <---
Dhuhr: 11:19 AM
Asr: 2:29 PM
Maghrib: 5:22 PM
Isha: 6:29 PM
Qiyam: 3:07 AM
```

I can get my Python version with [PyIslam](https://github.com/abougouffa/pyIslam) right. But I think need I need to pass more config to get this rust version right.

**I've tried following ways**, but can't get it right. Because I don't find any example in the [docs](https://docs.rs/salah/0.4.2/salah/struct.Configuration.html) and readme.

``` diff
fn get_prayers_time() -> Result<salah::PrayerTimes, String> {
    let city = Coordinates::new(-7.1605439, 113.4826273);
    let date = Utc::today();
+    let params = Configuration::new()
+        .with(Method::Singapore, Madhab::Shafi);
    let prayers = PrayerSchedule::new()
        .on(date)
        .for_location(city)
        .with_configuration(params)
        .calculate();
    return prayers;
}

```

Also, I want to pass with other params such: `HighLatitudeRule`. 

How can I do this?

Thank you for salah.

### PR DESCRIPTION
**Pull request by azzamsa**
```
- fix: `SolarTime::setting_hour` fails with value < 0
- fix: add missing HighLatitudeRule in prelude 
```

### CODE REVIEW

**Comment by insha** [comment]
Thank you so much for the pull request. Would you be able to add a test or two around this issue that is being addressed?

**Comment by azzamsa** [comment]
My PR mostly contains @RagibHasin works.

IMHO, I think It's better for Ragib to open A PR himself. Since he did a lot of improvement.

**Comment by RagibHasin** [comment]
Sorry for delayed response. I'm having problem with internet connection. I think I can open a PR tomorrow with the requested test cases included.

Thanks everyone.

**Comment by insha** [comment]
@azzamsa and @RagibHasin I have reviewed the pull request. It is fine to go; but I would like to have the tests incorporated before it is merged. Let me know if this is possible and we will proceed accordingly.

Edit.1: I have reopened the original issue and linked to this pull request. Once the request is merged that issue will be closed out automatically.

Edit.2: I am stating the obvious and also just want to make sure that the issue is not that local and UTC times were being compared. Correct? Because the library only outputs results in UTC; which then will need to be converted to local time.

**Comment by RagibHasin** [comment]
@insha Actually the problem mainly revolves around UTC and local dates.
When at higher time zones (for me UTC+6) we make a date in UTC at Fajr time, It is still yesterday local and thus creates all the problem.

For instance, today Fajr time in Rajshahi, BD is 4:46 AM Local and Yesterday 10:46 PM UTC. This situation causes `prayer.current()` to fail and this failure cascades. But if we use Local times for public interface and UTC times for solar and other calculations as required, the problem vanishes.

Ideally I thought we should make this library generic over time zone for public API. But no time zone implements `now()` and `today()` except `Local` and `Utc`. So I think we are stuck to Local for now.

But beware, this would cause `prayer.current()` to fail if we are calculating for someplace other then home time zone. But I think then we would not use `prayer.current()`, would we?

My PR may come today or at most tomorrow, in sha Allah.

**Comment by azzamsa** [comment]
A little bit of story:

I am developing the CLI salah app on top of this. At first, it has 3 problems:

1) I can't access `HighLatitudeRule` and solved by adding it to `lib.rs`
2) I have the wrong farj time. This solved [this fix](https://github.com/insha/salah/pull/2/commits/89c234d67aee415cd50c8069aeffd491edd88ad2) by Ragib
3) I and my user reported that [the fajr time stuck](https://todo.sr.ht/~azzamsa/Bilal/1) and doesn't show the next prayer. This is solved by changing all `UTC` to `Local`. The root cause is because by using UTC all the prayer times happens on a different date. This is solved by Ragib in his [uptosniff](https://github.com/insha/salah/pull/3) branch.

---

In [uptosniff](https://github.com/insha/salah/pull/3) branch, Ragib solves the 3 mentioned issues and refactor the code to be more idiomatic. That PR is indeed huge, I don't have any idea if you can accept it.

**Comment by insha** [comment]
@azzamsa Please bear with me while I try to understand and work through each of the issues.

>     1. I can't access `HighLatitudeRule` and solved by adding it to `lib.rs`

This is fine.

>     2. I have the wrong farj time. This solved [this fix](https://github.com/insha/salah/pull/2/commits/89c234d67aee415cd50c8069aeffd491edd88ad2) by Ragib
>     3. I and my user reported that [the fajr time stuck](https://todo.sr.ht/~azzamsa/Bilal/1) and doesn't show the next prayer. This is solved by changing all `UTC` to `Local`. The root cause is because by using UTC all the prayer times happens on a different date. This is solved by Ragib in his [uptosniff](https://github.com/insha/salah/pull/3) branch.

This is interesting. The library is expecting a UTC date, therefore, when passing in the date for the calculation the _client_ needs to take the local date and convert it to UTC _before_ passing it on to the library. And once the result is received the _client_ needs to convert the resulting times for each of the prayers to the desired local time from the provided UTC time.

The use of UTC is stated in the readme file, [here](https://github.com/insha/salah#date), and [here](https://github.com/insha/salah#prayer-schedule). The use of UTC is required because there is too much idiosyncrasies between time zones. UTC provides a consistent and stable date for all calculations. Therefore, I am of the opinion that the _consumers_ of this library should be handling this complexity rather than the library itself. The main reason being that the handling of local time zone is dependent on the system that the client is targeting and supporting; thus it should be the _client's_ responsibility to do the appropriate conversion.

> That PR is indeed huge, I don't have any idea if you can accept it.

Indeed, this PR is large and is addressing multiple issues. It would be best to break this down into individual pull requests for each of the issues. If you haven't already please take a look at the [contributing guide](https://github.com/insha/salah/blob/master/CONTRIBUTING.md) for this project.

**Comment by insha** [comment]
Closing this merge request due to inactivity.

**Pull request closed without merging**
